/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import businessObject.ClientesBLL;
import dataAccess.ClientesDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gardu
 */
public class FormRecepcionista extends javax.swing.JFrame
{

    DefaultTableModel modelo = new DefaultTableModel();

    public FormRecepcionista()
    {
        initComponents();
        disenoRecepcion();
    }

    public void disenoRecepcion()
    {
        txtIdCliente.setEditable(false);
        listarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        cboEstatus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Apellido");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Direccion");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telefono ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Estatus");

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModificarActionPerformed(evt);
            }
        });

        cboEstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inactivo", "Activo" }));

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID", "Nombre", "Apellido", "Direccion", "Telefono", "Estatus"
            }
        ));
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaClientes);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setText("Para eliminar seleccione una fila");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(157, 40));

        jMenu1.setText("Clientes");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Vehiculos");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Citas");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jMenu3MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Cerrar Sesion");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mousePressed(java.awt.event.MouseEvent evt)
            {
                jMenu4MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnModificar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                            .addComponent(btnRegistrar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(48, 48, 48)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(txtApellido)
                                .addComponent(txtDireccion)
                                .addComponent(txtTelefono)
                                .addComponent(cboEstatus, 0, 133, Short.MAX_VALUE))))
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(btnEliminar))
                        .addGap(30, 30, 30)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed
        try
        {
            registrarCliente();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error \n Contacte al administrador");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tablaClientesMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaClientesMouseClicked
    {//GEN-HEADEREND:event_tablaClientesMouseClicked
        int fila = tablaClientes.rowAtPoint(evt.getPoint());
        txtIdCliente.setText(tablaClientes.getValueAt(fila, 0).toString());
        txtNombre.setText(tablaClientes.getValueAt(fila, 1).toString());
        txtApellido.setText(tablaClientes.getValueAt(fila, 2).toString());
        txtDireccion.setText(tablaClientes.getValueAt(fila, 3).toString());
        txtTelefono.setText(tablaClientes.getValueAt(fila, 4).toString());
        cboEstatus.setSelectedItem(tablaClientes.getValueAt(fila, 5).toString());
        btnRegistrar.setEnabled(false);

    }//GEN-LAST:event_tablaClientesMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModificarActionPerformed
    {//GEN-HEADEREND:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try
        {
            modificarCliente();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error\nContacte al administrador");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
        try
        {
            eliminarCliente();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrio un error\nContacte al administrador");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu2MousePressed
    {//GEN-HEADEREND:event_jMenu2MousePressed
        // TODO add your handling code here:
        new FormVehiculos().setVisible(true);
    }//GEN-LAST:event_jMenu2MousePressed

    private void jMenu3MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu3MousePressed
    {//GEN-HEADEREND:event_jMenu3MousePressed
        new FormCitas().setVisible(true);
    }//GEN-LAST:event_jMenu3MousePressed

    private void jMenu4MousePressed(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jMenu4MousePressed
    {//GEN-HEADEREND:event_jMenu4MousePressed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jMenu4MousePressed

    private void registrarCliente()
    {

        if (validarCampos())
        {
            ClientesBLL objCliente = new ClientesBLL();
            String nombre, apellido, direccion, telefono;
            int estatus = cboEstatus.getSelectedIndex();
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            direccion = txtDireccion.getText();
            telefono = txtTelefono.getText();
            boolean x = objCliente.crearCliente(nombre, apellido, direccion, telefono, estatus);
            if (x)
            {
                limpiarTablaClientes();
                listarClientes();
                limpiarCampos();
                JOptionPane.showMessageDialog(null, "Cliente Registrado");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se pudo registrar");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorioss");
        }

    }

    private void modificarCliente()
    {
        if (validarCampos())
        {
            ClientesBLL objCliente = new ClientesBLL();
            String nombre, apellido, direccion, telefono;
            int estatus = cboEstatus.getSelectedIndex();
            int idCliente = Integer.parseInt(txtIdCliente.getText());
            nombre = txtNombre.getText();
            apellido = txtApellido.getText();
            direccion = txtDireccion.getText();
            telefono = txtTelefono.getText();
            boolean x = objCliente.modificarCliente(idCliente, nombre, apellido, direccion, telefono, estatus);
            if (x)
            {
                limpiarTablaClientes();
                listarClientes();
                limpiarCampos();
                btnRegistrar.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Cliente modificado");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para modificar");
        }
    }

    private void eliminarCliente()
    {
        if (!verificarSeleccion())
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else
        {
            ClientesBLL clientebll = new ClientesBLL();
            int idCliente = Integer.parseInt(txtIdCliente.getText());
            boolean b = clientebll.eliminarCliente(idCliente);
            if (b)
            {
                limpiarTablaClientes();
                listarClientes();
                limpiarCampos();
                btnRegistrar.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Se elimino");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar");
            }
        }

    }

    public void limpiarCampos()
    {
        txtNombre.setText("");
        txtApellido.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtIdCliente.setText("");
    }

    public boolean validarCampos()
    {
        if (txtNombre.getText().equals("") || txtApellido.getText().equals("") || txtDireccion.getText().equals("") || txtTelefono.getText().equals(""))
        {
            return false;
        } else
        {
            return true;
        }

    }

    public void listarClientes()
    {
        try
        {
            ClientesBLL clienteBLL = new ClientesBLL();
            ArrayList<ClientesDto> lista = clienteBLL.mostrarClientes();
            modelo = (DefaultTableModel) tablaClientes.getModel();
            Object[] obj = new Object[6];

            for (int i = 0; i < lista.size(); i++)
            {
                obj[0] = lista.get(i).getIdCliente();
                obj[1] = lista.get(i).getNombre();
                obj[2] = lista.get(i).getApellido();
                obj[3] = lista.get(i).getDireccion();
                obj[4] = lista.get(i).getTelefono();
                obj[5] = lista.get(i).getEstatus();
                modelo.addRow(obj);
            }
            tablaClientes.setModel(modelo);
        } catch (Exception e)
        {
        }

    }

    public boolean verificarSeleccion()
    {
        return !txtIdCliente.getText().equals("");
    }

    public void limpiarTablaClientes()
    {
        for (int i = 0; i < modelo.getRowCount(); i++)
        {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboEstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
