package gui;

import businessObject.ClientesBLL;
import businessObject.VehiculosBLL;
import dataAccess.ClientesDto;
import dataAccess.VehiculosDto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gardu
 */
public class FormVehiculos extends javax.swing.JFrame
{

    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form FormVehiculos
     */
    public FormVehiculos()
    {
        initComponents();
        disenoVehiculos();
    }

    public void disenoVehiculos()
    {
        listarVehiculos();
        txtIdVehiculo.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtMotor = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextPane();
        txtIdVehiculo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        jLabel3.setText("Matricula");

        jLabel5.setText("Motor");

        jLabel6.setText("Diagnostico");

        jLabel7.setText("ID Cliente");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnModificarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRegistrarActionPerformed(evt);
            }
        });

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID Vehiculo", "Marca", "Modelo", "Matricula", "Motor", "Diagnostico", "ID Cliente"
            }
        ));
        tablaVehiculos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tablaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVehiculos);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Vehiculos");

        jScrollPane3.setViewportView(txtDiagnostico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnModificar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRegistrar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtModelo)
                                                .addComponent(txtMatricula)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtIdVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnRegistrar)
                    .addComponent(btnEliminar))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tablaVehiculosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tablaVehiculosMouseClicked
    {//GEN-HEADEREND:event_tablaVehiculosMouseClicked
        // TODO add your handling code here:
        int fila = tablaVehiculos.rowAtPoint(evt.getPoint());
        txtIdVehiculo.setText(tablaVehiculos.getValueAt(fila, 0).toString());
        txtMarca.setText(tablaVehiculos.getValueAt(fila, 1).toString());
        txtModelo.setText(tablaVehiculos.getValueAt(fila, 2).toString());
        txtMatricula.setText(tablaVehiculos.getValueAt(fila, 3).toString());
        txtMotor.setText(tablaVehiculos.getValueAt(fila, 4).toString());
        txtDiagnostico.setText(tablaVehiculos.getValueAt(fila, 5).toString());
        txtIdCliente.setText(tablaVehiculos.getValueAt(fila, 6).toString());
        btnRegistrar.setEnabled(false);

    }//GEN-LAST:event_tablaVehiculosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnModificarActionPerformed
    {//GEN-HEADEREND:event_btnModificarActionPerformed
        // TODO add your handling code here:

        try
        {
            modificarVehiculo();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrió un error\nContacte al administrador");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRegistrarActionPerformed
    {//GEN-HEADEREND:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try
        {
            registrarVehiculo();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrió un error\nContacte al administrador");
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnEliminarActionPerformed
    {//GEN-HEADEREND:event_btnEliminarActionPerformed
        try
        {
            eliminarVehiculo();
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, "Ocurrió un error\nContacte al administrador");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    public void registrarVehiculo()
    {
        if (!validarCampos())
        {
            VehiculosBLL vehbll = new VehiculosBLL();
            String marca, modelo, matricula, motor, diagnostico;
            int idCliente = Integer.parseInt(txtIdCliente.getText());
            marca = txtMarca.getText();
            modelo = txtModelo.getText();
            matricula = txtMatricula.getText();
            motor = txtMotor.getText();
            diagnostico = txtDiagnostico.getText();
            boolean x = vehbll.crearVehiculo(marca, modelo, matricula, motor, diagnostico, idCliente);
            if (x)
            {
                limpiarTablaVehiculos();
                listarVehiculos();
                limpiarCampos();
                JOptionPane.showMessageDialog(null, "Se registró correctamente");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se registró");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        }

    }

    public void modificarVehiculo()
    {
        if (!validarCampos())
        {
            VehiculosBLL vehbll = new VehiculosBLL();
            String marca, modelo, matricula, motor, diagnostico;
            int idVehiculo = Integer.parseInt(txtIdVehiculo.getText());
            int idCliente = Integer.parseInt(txtIdCliente.getText());
            marca = txtMarca.getText();
            modelo = txtModelo.getText();
            matricula = txtMatricula.getText();
            motor = txtMotor.getText();
            diagnostico = txtDiagnostico.getText();
            boolean x = vehbll.modificarVehiculo(idVehiculo, marca, modelo, matricula, motor, diagnostico, idCliente);
            if (x)
            {
                limpiarTablaVehiculos();
                listarVehiculos();
                limpiarCampos();
                btnRegistrar.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Se modificó correctamente");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se modificó");
            }
        } else
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }

    }

    public void listarVehiculos()
    {
        try
        {
            VehiculosBLL vehiculo = new VehiculosBLL();
            ArrayList<VehiculosDto> lista = vehiculo.mostrarVehiculos();
            modelo = (DefaultTableModel) tablaVehiculos.getModel();
            Object[] obj = new Object[7];

            for (int i = 0; i < lista.size(); i++)
            {
                obj[0] = lista.get(i).getIdVehiculo();
                obj[1] = lista.get(i).getMarca();
                obj[2] = lista.get(i).getModelo();
                obj[3] = lista.get(i).getMatricula();
                obj[4] = lista.get(i).getMotor();
                obj[5] = lista.get(i).getDiagnostico();
                obj[6] = lista.get(i).getIdCliente();
                modelo.addRow(obj);
            }
            tablaVehiculos.setModel(modelo);
        } catch (Exception e)
        {
        }

    }

    public void eliminarVehiculo()
    {
        if (verificarSeleccion())
        {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        } else
        {
            VehiculosBLL vehiculobll = new VehiculosBLL();
            int idVehiculo = Integer.parseInt(txtIdVehiculo.getText());
            boolean b = vehiculobll.eliminarVehiculo(idVehiculo);
            if (b)
            {
                limpiarTablaVehiculos();
                listarVehiculos();
                limpiarCampos();
                btnRegistrar.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Se elimino");
            } else
            {
                JOptionPane.showMessageDialog(null, "No se pudo eliminar");
            }
        }

    }

    public void limpiarTablaVehiculos()
    {
        for (int i = 0; i < modelo.getRowCount(); i++)
        {
            modelo.removeRow(i);
            i = i - 1;
        }
    }

    public boolean verificarSeleccion()
    {
        return txtIdVehiculo.getText().equals("");
    }

    public void limpiarCampos()
    {
        txtIdCliente.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtMatricula.setText("");
        txtMotor.setText("");
        txtDiagnostico.setText("");
        txtIdVehiculo.setText("");
    }

    private boolean validarCampos()
    {
        return txtMarca.getText().equals("") || txtModelo.getText().equals("") || txtMatricula.getText().equals("")
                || txtMotor.getText().equals("") || txtDiagnostico.getText().equals("") || txtIdCliente.getText().equals("");
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JTextPane txtDiagnostico;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdVehiculo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    // End of variables declaration//GEN-END:variables
}
